# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - git config --local core.hooksPath .githooks/
  build:
    cmds:
      - dotnet build
  test:
    deps: [build]
    cmds:
      - dotnet test --no-build
  rebuild:
    cmds:
      - dotnet clean
      - dotnet build-server shutdown
      - dotnet build
  new-message:
    silent: true
    interactive: true
    cmds:
      - .scripts/new-message.sh
  new-request:
    silent: true
    interactive: true
    cmds:
      - .scripts/new-request.sh