# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - git config --local core.hooksPath .githooks/
  new-message:
    silent: true
    interactive: true
    cmds:
      - .scripts/new-message.sh
  new-request:
    silent: true
    interactive: true
    cmds:
      - .scripts/new-request.sh
  test:
    deps: [build]
    cmds:
      - dotnet test --no-build
  build:
    cmds:
      - dotnet build
  rebuild:
    cmds:
      - dotnet clean
      - dotnet build-server shutdown
      - dotnet build
  pkg:clean:
    cmds:
      - rm -r ./pkg
  pkg:
    deps: [ pkg:clean ]
    cmds:
      - dotnet pack src/Xabbo.Core -c Release -o pkg
  pkg:push:
    deps: [ pkg ]
    cmds:
      - dotnet nuget push pkg/*.nupkg --api-key $(op read 'op://xabbo/nuget/credential') --source https://api.nuget.org/v3/index.json --skip-duplicate